### ISSUE TITLE
Event Detail Inscription Button Don't work

### ISSUE THREAD

**Issue by spaeres** [Moviles202320Grupo12/Unimaps_Kotlin#73]
**This button:**

<img width="413" alt="Captura de pantalla 2023-12-04 a la(s) 2 00 30 p  m" src="https://github.com/Moviles202320Grupo12/Unimaps_Kotlin/assets/69610038/686723bd-ca38-4ea2-81fa-c0c05b14852d">

**Comment by jmRiveral** [comment]
fixed
