### ISSUE TITLE
Tutors Detail Buttons Don't work

### ISSUE THREAD

**Issue by spaeres** [Moviles202320Grupo12/Unimaps_Kotlin#74]
**Tutors detail buttons**

<img width="440" alt="Captura de pantalla 2023-12-04 a la(s) 2 02 24 p  m" src="https://github.com/Moviles202320Grupo12/Unimaps_Kotlin/assets/69610038/e74fdd77-50b0-4cb4-81d4-bd2fffa94216">

**Comment by jmRiveral** [comment]
request now opens whats app, save later deleted
